apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: calciapp
  template:
    metadata:
      labels:
        app: calciapp
    spec:
      containers:
      - name: calapp
        image: tejachittamuri/calculator:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: calciapp
  ports:
  - port: 80
    targetPort: 80
