apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: omnifood
  template:
    metadata:
      labels:
        app: omnifood
    spec:
      containers:
      - name: omnifoodapp
        image:  tejachittamuri/ultimatecicd:2
        ports:
        - containerPort: 80
