apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
       app: voteapp
  template:
    metadata:
      labels:
       app: voteapp
    spec:
      containers:
      - name: result-container
        image: tejachittamuri/resultappui:v1
        ports:
         - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: LoadBalancer
  selector:
     app: voteapp
  ports:
  - port: 80
    targetPort: 80


