apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapp
  template:
    metadata:
      labels:
        app: voteapp
    spec:
      containers:
      - name: voteui-container
        image: tejachittamuri/voteappui:v1
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  selector:
   app: voteapp
  ports:
  - port: 80
    targetPort: 80


